Dockerfile
gpg commands create a gpg agent
one we have finished with gpg we should stop the process so the files
can be cleaned up
to doubly make sure we clean up tmp add an -f when we rm
solo @tlwr
=> BAU: Make build reproducible

src/files/sites.nginx
- adds request ids to /healthcheck and to /request-denied
- returns plain 400 instead of trying to look up html page that doesn't exist
solo @tlwr
=> BAU: Add request denied location block

src/files/naxsi_connector_whitelist.rules
By analysing our logs we have found rules that were being triggered by
legitimate stripe notifications. This commit relaxes the specific rules
for the specific attributes as per that analysis.
See https://payments-platform.atlassian.net/browse/PP-4375 for
details.
=> PP-4375 Add rules to allow stripe notifications

src/files/naxsi_connector_whitelist.rules
- For consistency, apply the same rules as in Public API `return_url` (related PR https://github.com/alphagov/pay-infra/pull/1936):
Cross-referencing with https://github.com/nbs-system/naxsi/blob/master/naxsi_config/naxsi_core.rules we're whitelisting the following:
1000: sql keywords
1002: 0x, possible hex encoding
1003: mysql comment (/*)
1004: mysql comment (*/)
1005: mysql keyword (|)
1006: mysql keyword (&&)
1007: mysql comment (--)
1008: semicolon
1009: equal sign in var, probable sql/xss
1010: open parenthesis
1011: close parenthesis
1013: simple quote
1015: comma
1016: mysql comment (#)
1017: double arobase (@@)
1100: http://
1101: https://
1200: double dot
1205: backslash
1302: html open tag
1303: html close tag
1310: open square backet ([)
1311: close square bracket (])
1312: …
=> PP-4757 NAXSI: rules for all *url properties for Stripe notifications

src/files/naxsi_connector_whitelist.rules
We are seeing stripe notifications being blocked because of `'` in
the line1 attribute (presumably of address) in some notification
payloads. This commit relaxes that rule. We have strong authentication
of stripe payloads, so we should err on side of laxity in this case.
=> PP-4833 Relax naxsi rules for stripe

src/files/naxsi_connector_whitelist.rules
Whitelist the following rules for the body of a Smartpay notification.
1009 - "="
1010 - "("
1011 - ")"
1012 - "\'"
Smartpay notifications come from a trusted URL and we do secret
validation on incoming requests to ensure this. Therefore, if the body
is well-formed JSON - which is enforced by NAXSI the risk is very low
of having any malicious content in the notification.
It appears that we are receiving Smartpay notifications containing
fields that we weren't previously receiving which is why we are having
to loosen the NAXSI rules.
with @heathd
=> PP-4936 Whitelist rules for body of Smartpay notifications

src/files/naxsi_connector_whitelist.rules
Whitelist the following rules for the body of a Stripe notification:
1010 - "("
1011 - ")"
1013 - "\'"
1015 - ","
1314 - "`"
Stripe notifications come from a trusted URL and we do secret
validation on incoming requests to ensure this. Therefore, if the body
is well-formed JSON, which is enforced by NAXSI, the risk is very low
of having any malicious content in the notification.
=> PP-4963 Whitelist rules for Stripe notification body

src/docker-startup.sh
If we don't have a keypair available at startup, generate one.
=> PP-5068: Generate a selfsigned certificate on startup if necessary

src/files/naxsi_connector_whitelist.rules
Whitelist all rules for the Stripe notification body that we whitelist for cardholder details fields in frontend.
=> PP-5135 Whitelist rules for Stripe notifications

Dockerfile
Upgrade our naxsi version from 0.55.3 to 0.56
At the same time, clean up the docker build by removing build dependencies, shrinking the container from ~200MB to ~15MB
=> PP-4748 Upgrade naxsi

Dockerfile
naxsi depends on pcre, which was previously installed as part of the build
dependencies. Now that we're removing build dependencies from the image, this
breaks naxsi with the following errors:
Error loading shared library libpcre.so.1: No such file or directory (needed by /usr/sbin/nginx)
Error relocating /usr/sbin/nginx: pcre_exec: symbol not found
Error relocating /usr/sbin/nginx: pcre_fullinfo: symbol not found
Error relocating /usr/sbin/nginx: pcre_config: symbol not found
Error relocating /usr/sbin/nginx: pcre_compile: symbol not found
Error relocating /usr/sbin/nginx: pcre_free_study: symbol not found
Error relocating /usr/sbin/nginx: pcre_study: symbol not found
Error relocating /usr/sbin/nginx: pcre_malloc: symbol not found
Error relocating /usr/sbin/nginx: pcre_free: symbol not …
=> PP-4748: Avoid uninstalling pcre

src/files/naxsi_connector_whitelist.rules
Add double-quotes rule to the whitelist for smartpay notifications body
1001 -> "
Zendesk ticket: https://govuk.zendesk.com/agent/tickets/3676084
Solo: @cobainc0
=> PP-5174 Whitelist NAXSI rule for Smartpay notification body

Dockerfile
So that we can have confidence our base images aren't being changed without our
knowledge, reference them by digest instead of tag (as tags are not immutable).
Also, add a comment detailing the tag the digest corresponds to.
=> RED-45: Reference base Docker images via digest

src/files/naxsi_dd_connector_whitelist.rules
We're blocking on rule 1002, as resource IDs in events can contain the string "0x". Whitelisting for all body fields as their are numerous different ids events could contain.
=> PP-3717 Whitelist rule for GoCardless webhooks

src/files/naxsi_connector_whitelist.rules
Do not apply rule 1002 'possible hex encoding' check to any field within
the notification from Stripe. There are many fields which have the potential
to include '0x' and since Stripe is a trusted party it seems practical to whitelist
this rule for the entire body rather than specific fields which may
change. We apply the same white listing of rule 1002 for Direct Debit
Connector Go Cardless webhook.
Associated Zendesk ticket is: 3807008
=> PP-5655 White list naxsi rule 1002 for stripe notifications

src/files/naxsi_connector_whitelist.rules
Rule 1015 is a comma
As notifications come from a whitelisted IP, we generally unblock rules
we're blocking on if it seems sensible that the notification could
contain the character we’re blocking on. In this case it does as the
field is 'operations' which suggests the value could be a comma
separated list.
=> PP-5843 Whitelist comma in body for smartpay notifications

src/files/naxsi_connector_whitelist.rules
We were blocking ePDQ notifications because there was a ";" in the "cn"
field. We whitelist rules we block on for notifications if it seems
reasonable as we have limited knowledge of what these fields could
contain and notifications are only allowed from a whitelisted IP.
=> PP-5867 Whitelist rule 1008 for ePDQ notifications

src/files/naxsi_dd_connector_whitelist.rules
We received the following NAXSI block alert
&uri=/v1/webhooks/gocardless&learning=0&vers=0.56&total_processed=296&total_blocked=1&block=1&cscore0=$SQL&score0=8&zone0=BODY&id0=1000&var_name0=action&zone1=BODY&id1=1000&var_name1=cause
Rule 1000 is sql keyword.
The field "action" in a webhook can contain the action "updated" which
is what NAXSI appears to be blocking on here.
=> BAU Whitelist rule 1000 for action field in GoCardless webhooks

src/files/naxsi_dd_connector_whitelist.rules
NAXSI’s is blocking GoCardless notifications because of rule 1000, which is SQL keywords, triggering for the `action` and `cause` fields.
It’s probably the word “updated” (like SQL’s `UPDATE`) appearing in the notifications in those fields.
The action field was whitelisted in https://github.com/alphagov/pay-notifications/pull/34. Whitelist `cause` as well and — for good measure — `description`.
=> Allow NAXSI 1000 for cause and description in GC notifications

src/files/naxsi_connector_whitelist.rules
We send the payment description to Stripe and they send it back in
webhooks.
We were blocking a webhook because the description contained ".." (rule
1200).
Whitelist all rules we allow for the description in payment creation
as the description could potentially violate any of these.
=> BAU - Whitelist rules for description field in Stripe notifications

src/files/naxsi_connector_whitelist.rules
We were blocking on rule 1008 (semicolon) for the merchantreference field.
For smartpay, we whitelist rules for all body fields as we don't really know what we're getting, so long as it seems sensible to.
=> BAU Whitelist rule 1008 for smartpay notifications

src/files/naxsi_connector_whitelist.rules
Whitelist rule 1000 for smartpay which restricted sql keywords and was
blocking the `authcode` in the body.
Whitelist rules for body of smartpay to align with address fields in frontend.
Whitelist rule 1001 for stripe which restricted double quotes and was
blocking on the `line1` field in the body.
zendesk ticket https://govuk.zendesk.com/agent/tickets/3954915
=> Zen desk 3954915 Whitelist smartpay and stripe notifications

src/files/naxsi_connector_whitelist.rules
The `cn` parameter in ePDQ notifications contains the cardholder name so we want to allow the same things we allow for the `cardholdername` field in frontend.
=> Zendesk 4070651 Update ePDQ notifications cn whitelist

Dockerfile
This was previously running Docker 3.10.
This PR also changes the long-form FROM line to include image tag and digest. This ensures Dependabot is able to correctly resolve the tag from the digest.
=> PP-6176: Update Alpine to 3.12.0

.secrets.baseline, LICENCE, README.md
Following the [GDS Way guidelines for Licence files](https://gds-way.cloudapps.digital/manuals/licensing.html#licensing).
This repo was also missing a secrets baseline file.
=> PP-7250 Add licence

Jenkinsfile
Given Jenkins doesn't do deployment anymore, this stage isn't needed.
=> PP-8696: Remove unneeded stage from Jenkinsfile

.github/workflows/build-notifications-image.yml, .github/workflows/post-merge.yml, .github/workflows/run-tests.yml
- Splits the single workflow into run-tests and post-merge release
- Adds concurrency to limit the post-merge workflow runs to one-at-a-time ([see pay-stubs for naming convention](https://github.com/alphagov/pay-stubs/commit/ab8ad7ca24e5d2cc4168055d8d16325d87bfb685).
=> PP-9376 Split release workflow and add concurrency

Dockerfile
The r0 releases have been removed from the apk registry. We also had to do this for the main nginx-proxy image - see https://github.com/alphagov/pay-nginx-proxy/pull/62.
=> BAU: Bump nginx release numbers

Dockerfile, src/files/naxsi_connector_whitelist.rules
- Noticed that stripe notifications are blocked on below rules (for last 7 days) which will impact payment journey.
1001 - double quote (postal_code - example YO32 \"rh)
1101 - https scheme (https://support.stripe.com/ in message)
1200 - double dot (city field - example: lancing.. west sussex)
- Also bumps nginx modules to the latest version
=> BAU - Whitelist rules for Stripe notifications & bump nginx module versions

src/files/sites.nginx, tests/notifications-test.js
Replace the default nginx placeholder pages with redirects to existing pages. Hitting the root of the service now sends you to https://payments.service.gov.uk/, and requesting a non-existent page sends you to https://gov.uk/404.
/ sends a 301. 404 uses the default nginx redirect method, which sends the user a 302. If you follow the 302, gov.uk will serve up a 404, but if you take it at face value -- like the tests do -- you get the 302. If this is not acceptable, please flag it now!
=> PP-11316-replace-default-page-with-redirect

src/files/naxsi_connector_whitelist.rules
1. Remove rules for endpoints for past suppliers
2. Allow a couple of extra rules through to avoid erroneously blocked requests
=> PP-12614: Allow equals and double encoding in body fields

Dockerfile, src/files/naxsi_connector_whitelist.rules
Allow `/*` (NAXSI rule 1003) and `*/` (NAXSI rule 1004) in Stripe webhook message bodies. It’s safe to allow these and we are receiving webhook messages that contain `/*` in the line1 parameter in the body.
=> ZD-5838986 Allow /* and */ in Stripe webhook message bodies

Dockerfile, src/files/naxsi_connector_whitelist.rules
Allow `--` (NAXSI rule 1007) and in Stripe webhook message bodies. It’s safe to allow and we’re receiving it in billing addresses in some notifications (presumably due to people mistyping Chorlton-cum-Hardy or similar).
=> ZD-5846430 Allow -- in Stripe webhook message bodies

.github/workflows/run-tests.yml
Upgrade `actions/checkout` to run on Node 20.
=> PP-12244: Upgrade deprecated checkout action to v4.2.2
